### ISSUE TITLE
BUG: ApplicationAuthenticationManager authenticates any user

### ISSUE THREAD

**Issue by kershov** [ericus20/spring-boot-starter#54]
Looks like any user will be authenticated regardless provided password. It doesn't seem that user's password is checked anywhere and seems that `SecurityConfig.SecurityConfig` doesn't work & `AuthenticationException` is not thrown when user provides wrong password.

**Comment by ericus20** [comment]
Thank you very much for your support. Looking into the issue right now.

**Comment by ericus20** [comment]
@kershov would you like to open a PR for the fix?

**Comment by kershov** [comment]
Opened: #55

**Comment by ericus20** [comment]
@kershov Thank you very much for the fix
