### ISSUE TITLE
Can't get token from postman

### ISSUE THREAD

**Issue by trancanh1102** [ericus20/spring-boot-starter#72]
i run the project successfully but when using post man to get token it seems error, where did i go wrong please help me

![image](https://user-images.githubusercontent.com/40576239/194033532-49d123cd-4115-4026-8f84-38d57b751ad8.png)

**Comment by ericus20** [comment]
@trancanh1102 Thank you very much for reporting this issue. This issue has been resolved.

![image](https://user-images.githubusercontent.com/20393990/198506892-c93bd96c-d725-433d-86f5-8aed6eb461fb.png)
