### ISSUE TITLE
Upgrade Dependencies in the Project

### ISSUE THREAD

**Issue by Arielpetit** [ericus20/spring-boot-starter#94]
I would like to suggest an upgrade for some dependencies in the project to enhance its performance and security. I believe that updating these dependencies could provide significant benefits, including improved functionality and access to the latest features.

I would be happy to take on the task of researching the necessary upgrades and implementing the changes. If this sounds good to you, please let me know, and I can provide a list of the dependencies I propose to update.

Thank you for considering my suggestion. I look forward to your feedback.

**Comment by Arielpetit** [comment]
Hi @ericus20 Please let me know if I can take on this issue and fix it!

**Comment by ericus20** [comment]
Hello @Arielpetit that's awesome and yes you can take on this issue and fix it. I appreciate your support

**Comment by Arielpetit** [comment]
Hi @ericus20 I created a Pull request
[Pull Request](https://github.com/ericus20/spring-boot-starter/pull/95)
